[package]
name = "day4"
version = "0.1.0"
authors = ["João Coutinho <j.afonso.coutinho@tecnico.ulisboa.pt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
